---
bundler_args: --without developer_workstation
script: bundle exec thor spec:ci
rvm:
- 1.9.3
- 2.0.0
- jruby-19mode
- jruby-head
- rbx-19mode
notifications:
  hipchat:
    secure: BdOAQHgi1RaQk8OyBbZzlgmrxVIF8RSYmDytZct4ynLrh8N19I/NeXTRFsnBlIcvRkWfrkztQ9YiGDS/IWoVvfLIz6Z3JJuDCE5AfrDdBFHRgjy0EeSxFoQYiKoaXkafdzCeN7lKs1uquU7SvFgE8o1zV9KiqYB2BuDqPkru3Kc=
